source xbian-arch for all needed info (and set dependency to latest -initramfs-tools package)

diff --git a/content-tpl/DEBIAN/postinst b/content-tpl/DEBIAN/postinst
--- a/content-tpl/DEBIAN/postinst
+++ b/content-tpl/DEBIAN/postinst
@@ -51,22 +51,10 @@ upgrade_wheezy_to_jessie()
 
 if [ $1 = "configure" ]; then
 
-    grep -q BCM2708 /proc/cpuinfo 2>/dev/null && config_platform=rpi
-    grep -q BCM2836 /proc/cpuinfo 2>/dev/null && config_platform=rpi
-    grep -q BCM2709 /proc/cpuinfo 2>/dev/null && config_platform=rpi2
-    grep -q "i.MX6" /proc/cpuinfo 2>/dev/null && config_platform=imx6
-    grep -q sun7i /proc/cpuinfo 2>/dev/null && config_platform=bpi
-    grep -q 'rpi2\-jessie' /etc/apt/sources.list.d/xbian.list && config_platform=rpi2
+    config_platform=$(xbian-arch revision)
 
-    version="";
-    if which lsb_release >/dev/null; then
-        version=$(lsb_release -c -s);
-    elif [ -f /etc/debian_version ]; then
-        grep -q "7\..*" /etc/debian_version && version="wheezy"
-        grep -q "8\..*" /etc/debian_version && version="jessie"
-    else
-        echo "could not determine running OS version"
-    fi
+    version=$(xbian-arch os)
+    [ $version != unknown ] || echo "could not determine running OS version"
 
     [ "$(xbian-arch 2>/dev/null)" = iMX6 -o "$config_platform" = imx6 ] && disrepos=devel || disrepos="staging devel"
     [ "$(xbian-arch 2>/dev/null)" = BPI -o "$config_platform" = bpi ] && disrepos=devel || disrepos="staging devel"
@@ -87,14 +75,6 @@ if [ $1 = "configure" ]; then
     for k in /var/tmp/xbian.key/*.key; do 
         apt-key add $k
     done
-
-    #### if already migrated RPI2 to Debian/Jessie, but didn't change xbian.list to rpi2-jessie, do it now
-    if [ "$version" = jessie ]; then
-        if grep -q '^deb.*debian.net' /etc/apt/sources.list && grep -q 'stable[ ]*main[ ]*rpi-jessie' /etc/apt/sources.list.d/xbian.list; then
-            sed -i 's/rpi-jessie/rpi2-jessie/g' /etc/apt/sources.list.d/xbian.list
-        fi
-        exit 0
-    fi
 
     [ "$version" = wheezy ] || exit 0
     upgrade_wheezy_to_jessie $config_platform
